table = "v_sta_bol_t"
schema = "maga"
id = [ "mov_id" ]

[data]
mov_id = "number?"
dati_azienda_denom = "text?"
dati_azienda_indir = "text?"
dati_azienda_cap = "text?"
dati_azienda_comune = "text?"
dati_azienda_prov = "text?"
dati_azienda_piva = "text?"
dati_azienda_telef = "text?"
tipo_doc_mag = "text?"
tipo_doc_dex = "text?"
numero = "text?"
del = "text?"
controp_denom = "text?"
controp_indirizzo = "text?"
controp_cap = "text?"
controp_comune = "text?"
controp_provincia = "text?"
controp_cfisc = "text?"
controp_piva = "text?"
partenza_dicitura = "text?"
partenza_denom = "text?"
partenza_indir = "text?"
partenza_cap_etc = "text?"
partenza_telef = "text?"
destinaz_dicitura = "text?"
destinaz_denom = "text?"
destinaz_indir = "text?"
destinaz_cap_etc = "text?"
destinaz_telef = "text?"
tot_imponibile = "text?"
tot_imposta = "text?"
tot_documento = "text?"
dicitura_caus_del_trasp = "text?"
dicitura_cons_tramite = "text?"
dicitura_data_consegna = "text?"
dicitura_firma = "text?"
frase_finale = "text?"

  [data.righe]
  id = [ "auto" ]
  schema = "maga"
  table = "v_sta_bol_r"

    [data.righe.data]
    id = "number?"
    mov_id = "number?"
    riga = "number?"
    rif_odv = "text?"
    articolo = "text?"
    descrizione = "text?"
    um = "text?"
    qta = "number?"
    odv_riga_id = "number?"
    odv_id = "number?"
