table = "v_cond_voci"
schema = "base"
id = [ "id" ]

[data]
id = "number"
condiz_id = "number"
fornitore_id = "number"
fornitore_dex = "text"
categ_id = "number?"
categ_dex = "text?"
marchio = "text?"
linea = "text?"
gg_cons = "number?"
gg_cons_max = "number?"
sconto_cascata = "text?"
sconto_acq = "number?"
note = "text?"
pag_cod = "text?"
pag_dex = "text?"
sc_su_pag = "number?"
porto_franco = "bool?"
sp_trasp_ddt = "number?"
sp_trasp_perc = "number?"
prz_catal_ivato = "bool?"
oda_differito = "bool?"
secondario = "bool?"
