table = "v_articoli_lase"
schema = "base"
id = [ "articolo_id" ]

[data]
articolo_id = "number"
cat_dex = "text?"
marchio = "text?"
linea = "text?"
codice = "text?"
art_dex = "text?"
um = "text"
tipo_art_cod = "text"
tipo_art_dex = "text"
stato = "text?"
stato_dex = "text?"
qualifica_id = "number?"
qualifica_dex = "text?"
ore_per_unita = "number?"
prz_orario_assunto = "number?"
prezzo_listino = "number?"
prezzo_acq_netto = "number?"
prezzo_vendita = "number?"
da_attualizzare = "bool"
