table = "v_mov_righe"
schema = "maga"
id = [ "mov_riga_id" ]

[data]
mov_id = "number"
mov_riga_id = "number"
controp_id = "number?"
sede_cod = "text?"
magazzino_cod = "text?"
sede = "text?"
causale = "text?"
magazzino = "text?"
controparte = "text?"
data_mov = "text?"
nr_doc_ricevuto = "text?"
articolo = "text?"
riferimento = "text?"
um = "text?"
nr_documento = "text?"
dex_estesa = "text?"
ubicaz_id = "number?"
art_id = "number?"
qta = "number?"
colli_arrivati = "number?"
