table = "v_odv_righe_ass_cons"
schema = "vend"
id = [ "odv_riga_id" ]

[data]
odv_id = "number"
gru_cons_id = "number?"
odv_riga_id = "number"
art_id = "number"
progetto_id = "number?"
struttura_id = "number?"
gru_cons_nr = "number?"
item = "text?"
item_d = "text?"
sub_dex = "text?"
um = "text"
qta = "number?"
fonte = "text?"
fonte_dex = "text?"
fonte_cod_un = "text?"
cons_prevista = "text?"
tipo_art = "text"
tipo_riga = "text"
ore_per_unita = "number?"
qualifica_id = "number?"
qualifica_dex = "text?"
gru_cons_dex = "text?"
assegnato = "bool?"
arrivato_eseguito = "bool?"
usato = "bool?"
azione_per_mat = "text?"
oda_da_emettere = "bool"
destinaz_per_mat = "[object Object] list"
abilitato_a = "text?"
odt_id = "number?"
odl_id = "number?"
oda_id = "number?"
