table = "v_odv"
schema = "vend"
id = [ "odv_id" ]

[data]
odv_id = "number"
venditore_id = "number?"
cliente_id = "number?"
tipo = "text?"
tipo_cod_dom = "text?"
tipo_decod = "text?"
numero = "text?"
del = "date?"
dex = "text?"
denom = "text?"
indirizzo = "text?"
comune = "text?"
provincia = "text?"
cap = "text?"
cellulare = "text?"
telefono = "text?"
email = "text?"
estremi = "text?"
stato_dex = "text?"
sede = "text?"
sede_dex = "text?"
venditore_dex = "text?"
chiuso = "bool?"
numero_est_mancante = "bool?"
