table = "v_art_vend"
schema = "base"
id = [ "art_id" ]

[data]
art_id = "number"
cat_dex = "text?"
marchio = "text?"
linea = "text?"
codice = "text?"
art_dex = "text?"
um = "text?"
cod_iva = "text?"
cond_voce_id = "number?"
categ_id = "number?"
prezzo = "number?"
modif_marchio = "bool?"
modif_linea = "bool?"
modif_codice = "bool?"
modif_dex = "bool?"
obblig_marchio = "bool?"
obblig_linea = "bool?"
obblig_codice = "bool?"
obblig_dex = "bool?"
obblig_dex2 = "bool?"
