table = "v_art_cond"
schema = "base"
id = [ "art_id" ]

[data]
art_id = "number"
cat_dex = "text?"
marchio = "text?"
linea = "text?"
codice = "text?"
art_dex = "text?"
um = "text"
tipo_art_cod = "text?"
tipo_art_dex = "text?"
univoco = "bool"
stato = "text?"
stato_dex = "text?"
fornitore = "text?"
cond_voce_id = "number?"
gg_cons = "number?"
gg_cons_max = "number?"
sconto_cascata = "text?"
sconto_acq = "number?"
pag_cod = "text?"
condizioni_dex = "text?"
cond_voce_art_id = "number?"
prezzo_list = "number?"
prz_acq_netto = "number?"
prezzo_vend = "number?"
moltiplicatore_arrot = "number?"
cod_art_forn = "text?"
