table = "v_odl_testate"
schema = "lase"
id = [ "numero" ]

[data]
numero = "number"
sede = "text?"
sede_dex = "text?"
riferimento = "text?"
indirizzo_cliente = "text?"
cdl_id = "number?"
centro_lavoro = "text?"
tipo_odl = "text?"
tipo_odl_dex = "text?"
responsab_id = "number?"
responsab_dex = "text?"
odl_dex = "text?"
del = "text?"
stato_dex = "text?"
note_chiusura = "text?"
note_contestaz = "text?"
richiesto_contatto = "bool?"
contiene_interventi = "bool"
chiuso = "bool"
