table = "v_odl_interventi"
schema = "lase"
id = [ "id" ]

[data]
odl_id = "number"
id = "number"
interv_dex = "text?"
data_interv = "date?"
data_interv_dex = "text?"
ora_interv_dex = "text?"
per_ore = "number?"
livello = "text?"
livello_dex = "text?"
presso = "text?"
presso_dex = "text?"
appunt_preso = "bool?"
ora_appunt = "text?"
appunt_preso_con = "text?"
appunt_preso_da_id = "number?"
appunt_preso_da_nome = "text?"
appunt_preso_da_il = "text?"
appunt_note = "text?"
stato_dex = "text?"
terminato = "bool?"
fino_a = "text?"
note_chiusura = "text?"
chiuso = "bool"
